import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
// solc-js ships no types; its surface here is one function.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const solc = require('solc') as {
  version(): string;
  compile(input: string): string;
};

/**
 * Compiles `contracts/PaymentForwarder.sol` and writes its creation bytecode to
 * `src/evm/payment-forwarder.artifact.ts`, which is committed.
 *
 *   npm run contracts:compile
 *
 * The bytecode is not an implementation detail: every deposit address is
 * `CREATE2(salt, keccak(bytecode ++ args))`, so a different compile is a
 * different set of addresses. The artifact is therefore generated once and
 * reviewed like code, and `payment-forwarder.artifact.spec.ts` recompiles the
 * source with the recorded settings and fails if the two disagree. Never edit
 * the artifact by hand; never recompile to a new artifact while deposit
 * addresses built from the old one still hold money.
 */
const ROOT = join(__dirname, '..');
const SOURCE_PATH = join(ROOT, 'contracts', 'PaymentForwarder.sol');
const ARTIFACT_PATH = join(ROOT, 'src', 'evm', 'payment-forwarder.artifact.ts');

/** Recorded in the artifact; the spec recompiles with exactly these. */
const SETTINGS = {
  optimizer: { enabled: true, runs: 200 },
  evmVersion: 'cancun',
  // No metadata hash: it would bake the source path and comments into the
  // bytecode, and with it into every deposit address.
  metadata: { bytecodeHash: 'none' },
  outputSelection: { '*': { PaymentForwarder: ['evm.bytecode.object'] } },
};

function main(): void {
  const source = readFileSync(SOURCE_PATH, 'utf8');
  const output = JSON.parse(
    solc.compile(
      JSON.stringify({
        language: 'Solidity',
        sources: { 'PaymentForwarder.sol': { content: source } },
        settings: SETTINGS,
      }),
    ),
  ) as {
    errors?: { severity: string; formattedMessage: string }[];
    contracts: Record<
      string,
      Record<string, { evm: { bytecode: { object: string } } }>
    >;
  };
  const errors = (output.errors ?? []).filter((e) => e.severity === 'error');
  if (errors.length > 0) {
    throw new Error(errors.map((e) => e.formattedMessage).join('\n'));
  }
  const bytecode =
    output.contracts['PaymentForwarder.sol'].PaymentForwarder.evm.bytecode
      .object;
  const sourceSha256 = createHash('sha256').update(source).digest('hex');

  writeFileSync(
    ARTIFACT_PATH,
    `/**
 * GENERATED by \`npm run contracts:compile\` from contracts/PaymentForwarder.sol.
 * Do not edit: every deposit address is derived from this bytecode.
 */
export const PAYMENT_FORWARDER_ARTIFACT = {
  compiler: '${solc.version()}',
  settings: ${JSON.stringify(SETTINGS)},
  sourceSha256: '${sourceSha256}',
  bytecode:
    '0x${bytecode}',
} as const;
`,
  );
  console.log(`PaymentForwarder compiled (${bytecode.length / 2} bytes)`);
}

main();
